import { useEffect, useState } from 'react'
import { ArrowDownRight, ArrowUpRight, Crosshair, Menu, X } from 'lucide-react'
import Globe from './components/Globe'
import { dataProvider } from './services/dataProvider'
import { protocolFeatures, roadmap } from './data/mockData'

const nav = [['01','HOME'],['02','NETWORK'],['03','PROTOCOL'],['04','EXCHANGE'],['05','ROADMAP'],['06','DOCS']]
const fmt = m => m.format==='percent'?`${m.value}%`:m.format==='volume'?`$${m.value}M`:m.value.toLocaleString()
function Spark({points}) { const max=Math.max(...points), d=points.map((p,i)=>`${i?'L':'M'}${i*14},${30-p/max*26}`).join(' '); return <svg className="spark" viewBox="0 0 100 32"><path d={d}/></svg> }
function Label({children,n='SYS'}) { return <div className="eyebrow"><span>[ {n} ]</span>{children}</div> }

export default function App(){
 const [mobile,setMobile]=useState(false), [modal,setModal]=useState(false), [metrics,setMetrics]=useState([]), [activity,setActivity]=useState([])
 useEffect(()=>{dataProvider.getMetrics().then(setMetrics); dataProvider.getActivity().then(setActivity)},[])
 useEffect(()=>{if(!activity.length)return;const id=setInterval(()=>setActivity(items=>dataProvider.refreshActivity(items)),3500);return()=>clearInterval(id)},[activity.length])
 useEffect(()=>{const obs=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.12});document.querySelectorAll('.reveal').forEach(x=>obs.observe(x));return()=>obs.disconnect()},[])
 return <main>
  <div className="noise"/><header><a className="brand" href="#home"><img src={`${import.meta.env.BASE_URL}assets/logo-placeholder.svg`}/><span>CHANGE<br/><small>NETWORK</small></span></a><nav>{nav.map(([n,x])=><a key={x} href={`#${x.toLowerCase()}`}><i>[{n}]</i>{x}</a>)}</nav><div className="head-actions"><span className="online"><b/> NETWORK ONLINE</span><button onClick={()=>setModal(true)}>CONNECT WALLET <ArrowUpRight size={14}/></button></div><button className="menu" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button></header>
  {mobile&&<div className="mobile-nav">{nav.map(([n,x])=><a key={x} onClick={()=>setMobile(false)} href={`#${x.toLowerCase()}`}>[{n}] {x}</a>)}</div>}
  <section className="hero" id="home"><div className="hero-copy"><Label n="CHG.01">DECENTRALIZED INFRASTRUCTURE</Label><h1><span>CHANGE</span><br/>EVERYTHING<br/>CHANGES<span className="green">.</span></h1><p>A NETWORK BUILT FOR A WORLD<br/>THAT NEVER STOPS CHANGING.</p><a className="discover" href="#network">ENTER THE NETWORK <ArrowDownRight/></a></div><div className="hero-visual"><div className="visual-top">LIVE NETWORK TOPOLOGY <span>01—06</span></div><Globe/><div className="visual-bottom"><span>REAL-TIME NODE MAP</span><span>LATENCY 12MS</span><span>UTC 08:42:17</span></div></div><div className="scroll">SCROLL TO EXPLORE <i/></div></section>
  <section className="metrics" id="network">{metrics.map((m,i)=><div className="metric" key={m.label}><Label n={`0${i+1}`}>{m.label}</Label><div className="metric-row"><strong>{fmt(m)}</strong><span>{m.change}</span></div><Spark points={m.points}/></div>)}</section>
  <section className="network section reveal"><div className="section-title"><div><Label n="NET.02">REAL-TIME DATA STREAM</Label><h2>LIVE<br/><em>NETWORK</em></h2></div><p>Distributed activity across the CHANGE network.<br/><span>Simulation feed / mock data</span></p></div><div className="table"><div className="tr th"><span>AMOUNT</span><span>ACTIVITY</span><span>REGION</span><span>NODE</span><span>STATUS</span><span>TIME</span></div>{activity.map(({id,row,time})=><div className="tr" key={id}>{row.map((v,i)=><span key={i} className={i===4?'status':''}>{i===4&&<b/>}{v}</span>)}<span>{time}</span></div>)}</div><div className="ticker">CHANGE NETWORK <i>●</i> ALL SYSTEMS OPERATIONAL <i>●</i> GLOBAL NODE FABRIC <i>●</i> MOCK DATA STREAM</div></section>
  <section className="protocol section" id="protocol"><div className="section-title reveal"><div><Label n="PRT.03">CORE SYSTEM</Label><h2>BUILT TO<br/><em>ADAPT.</em></h2></div><p>Modular infrastructure for an open,<br/>connected and continuously evolving world.</p></div><div className="feature-grid">{protocolFeatures.map(([n,t,d])=><article className="feature reveal" key={t}><span>[{n}]</span><Crosshair/><h3>{t}</h3><p>{d}</p><ArrowUpRight className="arrow"/></article>)}</div></section>
  <Exchange/>
  <section className="roadmap section" id="roadmap"><div className="section-title reveal"><div><Label n="MAP.05">SYSTEM EVOLUTION</Label><h2>THE PATH<br/><em>FORWARD.</em></h2></div><p>Six phases. One continuously<br/>expanding network.</p></div><div className="phases">{roadmap.map(([n,t,d],i)=><article className="phase reveal" key={t}><div><span>PHASE {n}</span><b className={i<2?'active':''}>{i<2?'ACTIVE':'QUEUED'}</b></div><strong>{t}</strong><p>{d}</p><i>0{roadmap.length-i}</i></article>)}</div></section>
  <section className="docs section" id="docs"><Label n="DOC.06">KNOWLEDGE BASE</Label><div className="docs-grid"><div><h2>READ THE<br/><em>SYSTEM.</em></h2><p>An evolving technical overview of the CHANGE vision, network, protocol and open ecosystem.</p><button onClick={()=>setModal(true)}>OPEN WHITEPAPER <ArrowUpRight/></button></div><div className="doc-list">{['INTRODUCTION','VISION','NETWORK','PROTOCOL','CHANGE','ECOSYSTEM','ROADMAP'].map((x,i)=><div key={x}><span>0{i+1}</span>{x}<small>OVERVIEW</small><ArrowUpRight/></div>)}</div></div></section>
  <footer><div className="footer-brand"><img src={`${import.meta.env.BASE_URL}assets/logo-placeholder.svg`}/><strong>CHANGE</strong></div><p>EVERYTHING CHANGES.<br/>BUILD FOR WHAT COMES NEXT.</p><div><span>© 2026 CHANGE NETWORK</span><span>SIMULATED PRODUCT CONCEPT</span></div></footer>
  {modal&&<div className="modal" onClick={()=>setModal(false)}><div onClick={e=>e.stopPropagation()}><button onClick={()=>setModal(false)}><X/></button><Label n="STATUS">PRODUCT UPDATE</Label><h2>COMING<br/><em>SOON.</em></h2><p>The CHANGE network is currently in development.<br/>No wallet or funds are connected.</p><span className="blink">● STANDBY</span></div></div>}
 </main>
}

function Exchange(){const bars=[40,68,52,80,58,92,76,105,88,120,98,135,115,142,128,158];return <section className="exchange section" id="exchange"><div className="section-title reveal"><div><Label n="EXC.04">PRODUCT PREVIEW</Label><h2>CHANGE<br/><em>EXCHANGE.</em></h2></div><p>A precision terminal for a market<br/>that never stops moving.</p></div><div className="terminal reveal"><div className="term-head"><span>CHG / USD <b>+4.27%</b></span><span>MARKET <i>● LIVE PREVIEW</i></span><strong>COMING SOON</strong></div><div className="chart"><div className="price"><small>CHANGE PRICE</small><b>$ 0.08472</b><span>+$0.0034 (4.27%)</span></div><svg viewBox="0 0 800 260" preserveAspectRatio="none"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#b7ff2a" stopOpacity=".2"/><stop offset="1" stopColor="#b7ff2a" stopOpacity="0"/></linearGradient></defs><path className="area" d="M0 220 C90 210 100 145 180 170 S280 120 340 150 S430 90 500 115 S620 30 800 52 L800 260 L0 260Z"/><path d="M0 220 C90 210 100 145 180 170 S280 120 340 150 S430 90 500 115 S620 30 800 52"/></svg><div className="volume">{bars.map((h,i)=><i style={{height:h}} key={i}/>)}</div></div><div className="order"><h4>ORDER BOOK <span>CHG/USD</span></h4>{[['0.08488','12,840'],['0.08482','8,441'],['0.08479','21,084'],['0.08472','—'],['0.08468','17,400'],['0.08461','7,309']].map((r,i)=><div key={r[0]} className={i<3?'sell':'buy'}><span>{r[0]}</span><span>{r[1]}</span></div>)}</div><div className="trade"><h4>PLACE ORDER <span>LIMIT</span></h4><label>AVAILABLE <span>0.00 USD</span></label><div>PRICE <b>$ 0.08472</b></div><div>AMOUNT <b>0 CHG</b></div><button>CONNECT WALLET</button><small>Preview only. Trading is not active.</small></div></div></section>}
